# Generated by Django 5.0 on 2023-12-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='نام بازیگر')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='actors/', verbose_name='عکس بازیگر')),
            ],
            options={
                'verbose_name': 'بازیگر',
                'verbose_name_plural': 'بازیگران',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, unique=True, verbose_name='نام کارگردان')),
            ],
            options={
                'verbose_name': 'کارگردان',
                'verbose_name_plural': 'کارگردان\u200cها',
            },
        ),
    ]
