# Generated by Django 5.0 on 2023-12-30 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='فصل')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان قسمت')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی شده')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.movie', verbose_name='فیلم و سریال')),
            ],
            options={
                'verbose_name': 'قسمت',
                'verbose_name_plural': 'قسمت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='EpisodeQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4k', '4K')], max_length=50, verbose_name='کیفیت')),
                ('file', models.FileField(max_length=255, upload_to='episodes/', verbose_name='فایل')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='episode.episode', verbose_name='قسمت')),
            ],
            options={
                'verbose_name': 'کیفیت قسمت',
                'verbose_name_plural': 'کیفیت\u200cهای قسمت',
            },
        ),
    ]
