# Generated by Django 5.0 on 2023-12-28 08:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام بازیگر')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/Actor', verbose_name='عکس بازیگر')),
            ],
            options={
                'verbose_name': 'بازیگر',
                'verbose_name_plural': 'بازیگران',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True, verbose_name='نام کارگردان')),
            ],
            options={
                'verbose_name': 'کارگردان',
                'verbose_name_plural': 'کارگردان ها',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آیپی')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='آدرس فیلم')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('release_date', models.DateField(default=datetime.date.today, verbose_name='تاریخ اکران فیلم')),
                ('duration', models.PositiveIntegerField(help_text='مدت زمان فیلم به دقیقه', verbose_name='مدت زمان')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/', verbose_name='پوستر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('views', models.PositiveIntegerField(default=0)),
                ('actor', models.ManyToManyField(related_name='movies_actor', to='main.actor', verbose_name='بازیگران')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_directed', to='main.director', verbose_name='کارگردان')),
                ('genres', models.ManyToManyField(to='main.genre', verbose_name='ژانر')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(default=1, verbose_name='فصل')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان قسمت')),
                ('quality', models.CharField(default='HD', max_length=50, verbose_name='کیفیت')),
                ('file', models.FileField(max_length=255, upload_to='movies/', verbose_name='فایل')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.movie', verbose_name='سریال')),
            ],
            options={
                'verbose_name': 'قسمت',
                'verbose_name_plural': 'قسمت ها',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن')),
                ('rating', models.FloatField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='امتیاز')),
                ('approved', models.BooleanField(choices=[(True, 'تایید شده'), (False, 'تایید نشده')], default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.movie', verbose_name='فیلم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نقد و بررسی',
                'verbose_name_plural': 'نقدها و بررسی\u200cها',
            },
        ),
    ]
