# Generated by Django 5.0 on 2023-12-30 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast', '__first__'),
        ('category', '__first__'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آیپی')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='آدرس فیلم')),
                ('status', models.BooleanField(default=False, verbose_name='تاییدیه انتشار')),
                ('release_date', models.DateField(verbose_name='تاریخ اکران فیلم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('imdb_id', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='IMDb ID')),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='IMDb Rating')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='مدت زمان فیلم به دقیقه', null=True, verbose_name='مدت زمان')),
                ('poster', models.URLField(blank=True, max_length=500, null=True, verbose_name='پوستر')),
                ('views', models.PositiveIntegerField(default=0)),
                ('actor', models.ManyToManyField(blank=True, related_name='movies_actor', to='cast.actor', verbose_name='بازیگران')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='دسته بندی')),
                ('director', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cast.director', verbose_name='کارگردان')),
                ('genres', models.ManyToManyField(to='main.genre', verbose_name='ژانر')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.movie')),
                ('number_of_seasons', models.PositiveIntegerField(default=1, verbose_name='تعداد فصل\u200cها')),
                ('average_episode_duration', models.PositiveIntegerField(blank=True, help_text='میانگین مدت زمان هر قسمت به دقیقه', null=True, verbose_name='میانگین مدت زمان قسمت\u200cها')),
            ],
            options={
                'verbose_name': 'سریال',
                'verbose_name_plural': 'سریال\u200cها',
            },
            bases=('main.movie',),
        ),
        migrations.CreateModel(
            name='SingleMovie',
            fields=[
                ('movie_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.movie')),
                ('release_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='کشور اکران')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='زبان فیلم')),
            ],
            options={
                'verbose_name': 'فیلم سینمایی',
                'verbose_name_plural': 'فیلم سینمایی',
            },
            bases=('main.movie',),
        ),
        migrations.CreateModel(
            name='MovieNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='نکته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='main.movie', verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'نکته فیلم',
                'verbose_name_plural': 'نکات فیلم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن')),
                ('rating', models.FloatField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='امتیاز')),
                ('approved', models.BooleanField(choices=[(True, 'تایید شده'), (False, 'تایید نشده')], default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.movie', verbose_name='فیلم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نقد و بررسی',
                'verbose_name_plural': 'نقدها و بررسی\u200cها',
            },
        ),
    ]
