# Generated by Django 5.0 on 2023-12-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_movie_actor_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='IMDb ID'),
        ),
    ]
