# Generated by Django 5.0 on 2023-12-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_movie_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='مدت زمان فیلم به دقیقه', null=True, verbose_name='مدت زمان'),
        ),
    ]
