# Generated by Django 5.0 on 2023-12-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='نام بازیگر'),
        ),
        migrations.AlterField(
            model_name='director',
            name='full_name',
            field=models.CharField(max_length=500, unique=True, verbose_name='نام کارگردان'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='quality',
            field=models.CharField(default='HD', max_length=300, verbose_name='کیفیت'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=500, verbose_name='عنوان قسمت'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='آدرس فیلم'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=300, unique=True, verbose_name='عنوان'),
        ),
    ]
