# Generated by Django 5.0 on 2023-12-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_actor_name_alter_director_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='پوستر'),
        ),
    ]
